name: Publish

on:
  push:
    branches:
      - main
    tags: ["*"]

jobs:
  sbt:
    name: sbt publish
    runs-on: ubuntu-latest
    if: github.repository == 'apache/incubator-pekko-grpc'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8    

      - name: Publish
        run: |-
          cp .jvmopts-ci .jvmopts
          sbt +publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}

# TODO: Need to figure out where to publish gradle plugin, see https://github.com/apache/incubator-pekko-grpc/issues/40
#  gradle-plugin:
#    name: Release gradle plugin
#    runs-on: ubuntu-latest
#    if: github.repository == 'apache/incubator-pekko-grpc'
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
#          fetch-depth: 0
#
#      - name: Setup Java 8
#        uses: actions/setup-java@v3
#        with:
#          distribution: temurin
#          java-version: 8
#
#      - name: Publish Plugin to Gradle Plugin Repository
#        run: cd gradle-plugin && ./gradlew publishPlugins -Pgradle.publish.key='${{ secrets.GRADLE_PUBLISH_KEY }}' -Pgradle.publish.secret='${{ secrets.GRADLE_SECRET }}'

# TODO: Replace doc publishing with our own solution
#  documentation:
#    name: Documentation
#    runs-on: ubuntu-latest
#    if: github.repository == 'apache/incubator-pekko-grpc'
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
#          fetch-depth: 0
#
#      - name: Setup Java 8
#        uses: actions/setup-java@v3
#        with:
#          distribution: temurin
#          java-version: 8
#
#      - name: Cache Coursier cache
#        uses: coursier/cache-action@v6
#
#      - name: Publish
#        run: |-
#          eval "$(ssh-agent -s)"
#          echo $SCP_SECRET | base64 -d > /tmp/id_rsa
#          chmod 600 /tmp/id_rsa
#          ssh-add /tmp/id_rsa
#          cp .jvmopts-ci .jvmopts
#          sbt docs/publishRsync
#        env:
#          SCP_SECRET: ${{ secrets.SCP_SECRET }}
